In [14]:
sales = pd.read_csv("../data/sales_train_evaluation.csv")
calendar = pd.read_csv("../data/calendar.csv")

print("Sales shape:", sales.shape)
print("Calendar shape:", calendar.shape)

Sales shape: (30490, 1947)
Calendar shape: (1969, 14)

In [15]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [16]:
print(sales.columns[:10].tolist())

['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4']

In [17]:
# Step 1 — separate the identifier columns from the day columns
id_cols = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']
day_cols = [col for col in sales.columns if col.startswith('d_')]

print(f"Identifier columns: {len(id_cols)}")
print(f"Day columns: {len(day_cols)}")

Identifier columns: 6
Day columns: 1941

In [18]:
# Step 2 — melt wide format into long format
sales_long = sales.melt(
    id_vars=id_cols,
    value_vars=day_cols,
    var_name='d',
    value_name='sales'
)

print(f"Shape before melt: {sales.shape}")
print(f"Shape after melt:  {sales_long.shape}")
sales_long.head()

Shape before melt: (30490, 1947)
Shape after melt:  (59181090, 8)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [19]:
print(sales_long.shape)

(59181090, 8)

In [20]:
print(calendar.head())
print(calendar.shape)

         date  wm_yr_wk    weekday  wday  month  year    d event_name_1  \
0  2011-01-29     11101   Saturday     1      1  2011  d_1          NaN
1  2011-01-30     11101     Sunday     2      1  2011  d_2          NaN
2  2011-01-31     11101     Monday     3      1  2011  d_3          NaN
3  2011-02-01     11101    Tuesday     4      2  2011  d_4          NaN
4  2011-02-02     11101  Wednesday     5      2  2011  d_5          NaN

  event_type_1 event_name_2 event_type_2  snap_CA  snap_TX  snap_WI
0          NaN          NaN          NaN        0        0        0
1          NaN          NaN          NaN        0        0        0
2          NaN          NaN          NaN        0        0        0
3          NaN          NaN          NaN        1        1        0
4          NaN          NaN          NaN        1        0        1
(1969, 14)

In [21]:
# Merge calendar into sales_long on the 'd' column
sales_cal = sales_long.merge(calendar, on='d', how='left')

print(sales_cal.shape)
sales_cal.head()

(59181090, 21)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,NaN,NaN,NaN,NaN,0,0,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,NaN,NaN,NaN,NaN,0,0,0

In [22]:
print(sales_cal[['date', 'weekday', 'month', 'event_name_1', 'snap_CA', 'sales']].head(10))

         date   weekday  month event_name_1  snap_CA  sales
0  2011-01-29  Saturday      1          NaN        0      0
1  2011-01-29  Saturday      1          NaN        0      0
2  2011-01-29  Saturday      1          NaN        0      0
3  2011-01-29  Saturday      1          NaN        0      0
4  2011-01-29  Saturday      1          NaN        0      0
5  2011-01-29  Saturday      1          NaN        0      0
6  2011-01-29  Saturday      1          NaN        0      0
7  2011-01-29  Saturday      1          NaN        0     12
8  2011-01-29  Saturday      1          NaN        0      2
9  2011-01-29  Saturday      1          NaN        0      0

In [23]:
prices = pd.read_csv("../data/sell_prices.csv")
print(prices.shape)
print(prices.head())

(6841121, 4)
  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [24]:
sales_full = sales_cal.merge(prices, on=['store_id', 'item_id', 'wm_yr_wk'], how='left')

print(sales_full.shape)
sales_full.head()

(59181090, 22)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN